### ISSUE TITLE
[EPIC] Complete Library base setup

### ISSUE THREAD

**Issue by nramc** [nramc/geojson4j#3]
- [x] #4
- [x] SonarQube Integration
- [x] Code coverage
- [x] Git Issue template
- [x] JavaDoc option
- [x] Publish to OSS Sonar repository
- [x] Readme.md update
- [x] #10
- [x] logging mechanism - https://github.com/nramc/geojson4j/issues/5
- [x] #14
- [x] #22
- [x] #23
- [x] #25
- [x] #24
- [x] #26
